### ISSUE TITLE
Folder names

### ISSUE THREAD

**Issue by mgondan** [SWI-Prolog/contrib-protobufs#15]
Dear Peter,

(Not urgent at all. Not important either.)

As I wrote you in an email, I am currently trying to build an embedded swipl as an R package. The R build system complains that the folder names are too long. This is the output of R CMD build:

````
$ R CMD build rolog
    checking for file ‘rolog/DESCRIPTION’ … OK
    preparing ‘rolog’:
    checking DESCRIPTION meta-information … OK
    cleaning src
    checking for LF line-endings in source and make files and shell scripts
    checking for empty or unneeded directories
    building ‘rolog_1.0.tar.gz’

Warnung in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,
storing paths of more than 100 bytes is not portable:

‘rolog/src/swipl-devel/packages/protobufs/bootstrap/protoc_gen_prolog_pb/google/protobuf/compiler/plugin_pb.pl’

Warnung in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,
storing paths of more than 100 bytes is not portable:

‘rolog/src/swipl-devel/packages/protobufs/bootstrap/protoc_gen_prolog_pb/google/protobuf/descriptor_pb.pl’
````

Thank you for considering it, I know this is a strange request in 2021, and I am seriously wondering which systems they have in mind for portability.

Best wishes,

Matthias

**Comment by kamahen** [comment]
The only thing I can do is shrink the name of the directory `protoc_gen_prolog_pb` to something smaller. Would this be enough? The rest of the directory path is controlled by other systems (e.g., the `protobuf/compiler` part is from the protobuf compiler (package `libprotobuf-dev` on Ubuntu)) and their related naming conventions.

When I looked at the longest directory names, I got this (note that package `jpl` has even longer names):
```
$ find swipl-devel/build -type d | xargs -L 1 python3 -c 'import sys; print(len(sys.argv[1]), sys.argv[1])' | grep -v jpl | sort -rn | head -1
86 swipl-devel/build/home/library/protobufs/protoc_gen_prolog_pb/google/protobuf/compiler
```

(Question: why does your system show `‘rolog/` instead of `prolog/`?)

(As for why the R build system complains about paths longer than 100 bytes ... perhaps this is a bug in their system, or based on outdated issues? I know that Windows 10 doesn't like paths that are  more than ~255 bytes, which roughly corresponds to 100 double-byte characters in UTF8, although this can be worked around at the command line by prefixing with `\\?`)

**Comment by mgondan** [comment]
Dear Peter,

if you could rename protoc_gen_prolog_pb to something that a bit shorter, this will probably solve the issue. 1000 thanks, and sorry for bothering you.

Regarding your questions:


  *   rolog is the name of the R package. It’s a bridge between R and Prolog, therefore, rolog. Most people like the name 😊
  *   I don’t know there the 100 bytes are coming from. It’s in R’s build system, and it produces a warning, and my worry is that CRAN will not let my package in if it produces a warning.
  *   Strange that jpl is not reported.

Best wishes,

Matthias

Von: Peter ***@***.***>
Gesendet: Sonntag, 31. Oktober 2021 20:03
An: ***@***.***>
Cc: Matthias ***@***.***>; ***@***.***>
Betreff: Re: [SWI-Prolog/contrib-protobufs] Folder names (Issue #15)


The only thing I can do is shrink the name of the directory protoc_gen_prolog_pb to something smaller. Would this be enough? The rest of the directory path is controlled by other systems (e.g., the protobuf/compiler part is from the protobuf compiler (package libprotobuf-dev on Ubuntu)) and their related naming conventions.

When I looked at the longest directory names, I got this (note that package jpl has even longer names):

$ find swipl-devel/build -type d | xargs -L 1 python3 -c 'import sys; print(len(sys.argv[1]), sys.argv[1])' | grep -v jpl | sort -rn | head -1



86 swipl-devel/build/home/library/protobufs/protoc_gen_prolog_pb/google/protobuf/compiler



(Question: why does your system show ‘rolog/ instead of prolog/?)

(As for why the R build system complains about paths longer than 100 bytes ... perhaps this is a bug in their system, or based on outdated issues? I know that Windows 10 doesn't like paths that are more than ~255 bytes, which roughly corresponds to 100 double-byte characters in UTF8, although this can be worked around at the command line by prefixing with \\?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSWI-Prolog%2Fcontrib-protobufs%2Fissues%2F15%23issuecomment-955774853&data=04%7C01%7CMatthias.Gondan%40psy.ku.dk%7C21071b114b8f420b2cc008d99ca1181a%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637713037984154468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A8bS%2FI9PIGUuNsL0Doipg5Z4yqMlMWLzZWnxBPiX78o%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADABF6TVSY3JEMOFQS5MTG3UJWHHFANCNFSM5HCBJVRQ&data=04%7C01%7CMatthias.Gondan%40psy.ku.dk%7C21071b114b8f420b2cc008d99ca1181a%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637713037984164460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CU175EFzMYAkaED6DYGx8PmkJ3lY28WypwMzmDGngMA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMatthias.Gondan%40psy.ku.dk%7C21071b114b8f420b2cc008d99ca1181a%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637713037984174455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qmUNhzDxL1R%2Fz3okOJ9V9KU1hmxhH8pJOP95ewyauhQ%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMatthias.Gondan%40psy.ku.dk%7C21071b114b8f420b2cc008d99ca1181a%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637713037984174455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g%2BQ8%2BG7OP3BddcI%2Btm80zG1n6%2FryjeSnkOq%2BkP7ZVyg%3D&reserved=0>.


The only thing I can do is shrink the name of the directory protoc_gen_prolog_pb to something smaller. Would this be enough? The rest of the directory path is controlled by other systems (e.g., the protobuf/compiler part is from the protobuf compiler (package libprotobuf-dev on Ubuntu)) and their related naming conventions.

When I looked at the longest directory names, I got this (note that package jpl has even longer names):

$ find swipl-devel/build -type d | xargs -L 1 python3 -c 'import sys; print(len(sys.argv[1]), sys.argv[1])' | grep -v jpl | sort -rn | head -1

86 swipl-devel/build/home/library/protobufs/protoc_gen_prolog_pb/google/protobuf/compiler



(Question: why does your system show ‘rolog/ instead of prolog/?)

(As for why the R build system complains about paths longer than 100 bytes ... perhaps this is a bug in their system, or based on outdated issues? I know that Windows 10 doesn't like paths that are more than ~255 bytes, which roughly corresponds to 100 double-byte characters in UTF8, although this can be worked around at the command line by prefixing with \\?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSWI-Prolog%2Fcontrib-protobufs%2Fissues%2F15%23issuecomment-955774853&data=04%7C01%7CMatthias.Gondan%40psy.ku.dk%7C21071b114b8f420b2cc008d99ca1181a%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637713037984154468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=A8bS%2FI9PIGUuNsL0Doipg5Z4yqMlMWLzZWnxBPiX78o%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADABF6TVSY3JEMOFQS5MTG3UJWHHFANCNFSM5HCBJVRQ&data=04%7C01%7CMatthias.Gondan%40psy.ku.dk%7C21071b114b8f420b2cc008d99ca1181a%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637713037984164460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CU175EFzMYAkaED6DYGx8PmkJ3lY28WypwMzmDGngMA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMatthias.Gondan%40psy.ku.dk%7C21071b114b8f420b2cc008d99ca1181a%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637713037984174455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qmUNhzDxL1R%2Fz3okOJ9V9KU1hmxhH8pJOP95ewyauhQ%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMatthias.Gondan%40psy.ku.dk%7C21071b114b8f420b2cc008d99ca1181a%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637713037984174455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g%2BQ8%2BG7OP3BddcI%2Btm80zG1n6%2FryjeSnkOq%2BkP7ZVyg%3D&reserved=0>.
